// <auto-generated />
namespace CoursePlanner.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class thirdmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(thirdmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201709280932491_third migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
