// <auto-generated />
namespace CoursePlanner.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Secondbettermigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Secondbettermigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201709271324300_Second better migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
