//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseMessage
    {
        public BaseMessage()
        {
            this.RequestApprovalMessage = new HashSet<RequestApprovalMessage>();
            this.ResponseApprovalMessage = new HashSet<ResponseApprovalMessage>();
            this.Comment = new HashSet<Comment>();
        }
    
        public int BaseMessageID { get; set; }
        public int SenderID { get; set; }
        public int RecieverID { get; set; }
        public string MessageText { get; set; }
        public System.DateTime MessageSendDate { get; set; }
        public Nullable<System.DateTime> MessageReadDate { get; set; }
    
        public virtual Teacher TeacherReciever { get; set; }
        public virtual Teacher TeacherSender { get; set; }
        public virtual ICollection<RequestApprovalMessage> RequestApprovalMessage { get; set; }
        public virtual ICollection<ResponseApprovalMessage> ResponseApprovalMessage { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
    }
}
