//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseOccurrence
    {
        public CourseOccurrence()
        {
            this.CourseTeacher = new HashSet<CourseTeacher>();
            this.RequestApprovalMessage = new HashSet<RequestApprovalMessage>();
        }
    
        public int CourseOccurrenceID { get; set; }
        public string Year { get; set; }
        public Terms Term { get; set; }
        public Nullable<Periods> Period { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<int> NoOfStudents { get; set; }
        public Nullable<int> NoOfPassingStudents { get; set; }
        public Nullable<double> HST { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<Statuses> Status { get; set; }
        public int CourseID { get; set; }
        public Nullable<int> CourseResponsibleID { get; set; }
    
        public virtual ICollection<CourseTeacher> CourseTeacher { get; set; }
        public virtual Course Course { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<RequestApprovalMessage> RequestApprovalMessage { get; set; }
    }
}
