//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlanner.Models
{
    using System;
    
    public enum CourseCredits : int
    {
        C5 = 0,
        C7_5 = 1,
        C15 = 2,
        C30 = 3
    }
}
