//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.MessageToResponse = new HashSet<Message>();
        }
    
        public int MessageID { get; set; }
        public string MessageText { get; set; }
        public int SenderID { get; set; }
        public int RecieverID { get; set; }
        public System.DateTime MessageSendDate { get; set; }
        public Nullable<System.DateTime> MessageReadDate { get; set; }
        public Nullable<MessageType> MessageType { get; set; }
        public Nullable<int> CourseOccurrenceID { get; set; }
        public Nullable<bool> ApproveChanges { get; set; }
        public Nullable<int> ResponseMessageID { get; set; }
    
        public virtual CourseOccurrence CourseOccurrence { get; set; }
        public virtual ICollection<Message> MessageToResponse { get; set; }
        public virtual Message ResponseToMessage { get; set; }
        public virtual Teacher TeacherReciever { get; set; }
        public virtual Teacher TeacherSender { get; set; }
    }
}
