//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlanner.Models
{
    using System;
    
    public enum Periods : int
    {
        P1 = 0,
        P2 = 1,
        P3 = 2,
        P4 = 3,
        P1P2 = 4,
        P2P3 = 5,
        P3P4 = 6,
        P1P2P3 = 7,
        P2P3P4 = 8,
        P1P2P3P4 = 9
    }
}
