//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlanner.Models
{
    using System;
    
    public enum Positions : int
    {
        Professor = 0,
        SeniorLecturer = 1,
        JuniorLecturer = 2,
        PhDStudent = 3,
        TeachingAssistant = 4
    }
}
