//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestApprovalMessage
    {
        public RequestApprovalMessage()
        {
            this.ResponseApprovalMessage = new HashSet<ResponseApprovalMessage>();
        }
    
        public int RequestApprovalMessageID { get; set; }
        public int CourseOccurrenceID { get; set; }
        public int BaseMessageID { get; set; }
    
        public virtual BaseMessage BaseMessage { get; set; }
        public virtual CourseOccurrence CourseOccurrence { get; set; }
        public virtual ICollection<ResponseApprovalMessage> ResponseApprovalMessage { get; set; }
    }
}
