//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoursePlanner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseApprovalMessage
    {
        public int ResponseApprovalMessageID { get; set; }
        public bool Response { get; set; }
        public int BaseMessageID { get; set; }
        public int RequestApprovalMessageID { get; set; }
    
        public virtual BaseMessage BaseMessage { get; set; }
        public virtual RequestApprovalMessage RequestApprovalMessage { get; set; }
    }
}
